### PR TITLE
Create app skeleton

### PR DESCRIPTION
**Pull request by j4ckofalltrades**
Refs #3 

Build output:

```java
$ mvn clean install
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for vonage-starter 1.0.0:
[INFO] 
[INFO] vonage-starter ..................................... SUCCESS [  0.258 s]
[INFO] vonage-spring-boot-autoconfigure ................... SUCCESS [  0.846 s]
[INFO] voange-spring-boot-starter ......................... SUCCESS [  0.035 s]
[INFO] vonage-spring-boot-test-application ................ SUCCESS [  0.069 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by j4ckofalltrades** [comment]
@yallen011 Requesting review

**Review by slorello89 — CHANGES_REQUESTED** [review]
Hi @j4ckofalltrades - question (apologize not very experienced with spring) - the spec calls for `mvn clean build` to run successfully - and while `mvn clean install` does work for me - `mvn clean build` produces:
```[ERROR] Unknown lifecycle phase "build"```
@yallen011 may have a better sense than I do - is this actually intended to work on `mvn clean build` - because maven at least on my end doesn't seem to think build is a valid step

**Comment by j4ckofalltrades** [comment]
@slorello89 Yeah I assumed it was a typo, Maven does not have a `build` lifecycle phase by default - https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html.

This is also the same for the https://github.com/Nexmo/nexmo-spring-boot-starter repo (where this pull request is based on).

**Comment by yallen011** [comment]
@slorello89 yeah, @j4ckofalltrades is correct. That should be changed in the specs. it should be `mvn clean install`

**Comment by j4ckofalltrades** [comment]
PR has gone stale; marking as closed.

**Pull request closed without merging**
